#############-->>Enter the path to save automation report <--################
REMOTE_AUTOPATH = "/opt/product/testteam/Products/AUTOMATION/IMS/Automation_folder/delcom-script"
REMOTE_AUTOSCRIPT = "startstopscript.sh"



#############-->>SEAGULL path Details <--################
LD_LIBRARY_PATH= "/usr/local/bin"
SEAGULL_confpath= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SEAGULL/CONFIG"
SEAGULL_DICO= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SEAGULL/DICTIONARY/DIAMETER-S6A-S6D-GX-GY.xml"
SEAGULL_SCENPATH= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SEAGULL/SCENARIO"
SEAGULL_FILEPATH= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SEAGULL/FILES"
SEAGULL_LOGPATH= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SEAGULL/LOGS"
SEAGULL_COMPLOGPATH= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SEAGULL/COMPLETED_LOGS"
SEG_PROCESS="SEAGULL_PCRF"
SEAGULL_SLEEP=2
SEAGULL_TIMEOUT=60
SEAGULL_PIDGREP = "Background"
SEAGULL_STDERR_FILE = "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/stderr"

#############-->>SEAGULL DEFAULT SCENARIO NAME <--################
SEAGULL_SCENARIO_NAME="NONE"
DEFAULT_SEAGULL_SCENARIO="SEAGULL_SCENARIO"
SEAGULL_CONFIG_NAME="IMS_PCRF_AUTO_CONFIG"
SEAGULL_SESSION_ID=1
SEAGULL_SCENARIO_FILE="NONE"
SEAGULL_CONFIGURATION_FILE="NONE"



############-->>STATUS FLAGS-->>#############
PASS= "DONE"
FAIL= "FAIL"
NOPREDB= "NULL"
ID_RSA= "/root/.ssh/id_rsa"


############LD Library path#############
SEGENV= "export LD_LIBRARY_PATH=/usr/local/bin"
##############-msgchecK Validation#############
msgchk = "NO"
msgno = " "
##############-msgchecK Validation#############
PROGDIR = "/usr/local/bin"
SEG_WORKPATH = "/opt/product/AUTOMATION/PCRF/Master_script"
CMD_PASSFAIL = "ls -rt ${log_path}${/}${SCENARIO_FILE}* | tail -1"
GREP_STRING = "Scenario [TD]?????? passed"
TESTCASE_FILE = "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/seagull_automation-pcrf-delcom-cases.conf"
TEST_CASE_RESULT = "TEST"
