REMOTE_CDR_PATH= [ 
                   "/home/testteam/Products/AUTOMATION/IMS/P_CSCF/tdr/",
                   "/home/testteam/Products/AUTOMATION/IMS/I_CSCF/tdr/",
                   "/home/testteam/Products/AUTOMATION/IMS/S_CSCF/tdr/",
                   "/home/testteam/Products/AUTOMATION/IMS/TAS/tdr/",
                   "/opt/product/testteam/Products/AUTOMATION/HSS_IMS/release/tdr11/",
                   "/opt/product/testteam/Products/AUTOMATION/IMS/IMSRRBS/CDR_VOICE/",
                   "/home/testteam/Products//AUTOMATION/IMS/PCRF/tdr/"
                 ]

CDR_SERVER_ALIAS= [ "98_SERVER", "98_SERVER", "98_SERVER", "98_SERVER", "54_SERVER","54_SERVER", "98_SERVER" ]

###########-->>File name prefix of each logger in the result path<--######################################

CDR_GREP_PREFIX=[["*"], ["*"], ["*"], ["*"], ["*"], ["*"], ["*"]]

##########-->> Prefix that needs to be prefixed before log file in the result path<<--####################

CDRS_PREFIX=[["PCSCF"], ["ICSCF"], ["SCSCF"], ["TAS"], ["HLR"], ["IE1"], ["PCRF"]]

##############REFERENCE CDR PATH AND PATTERNS############################
######eg:-REF_CDR_PATH={ 
######                     "path1/":".txt" ,
######                     "path2/":".cdr" 
######                 }


REF_CDR_INPUT_ALIAS= [
                "PCSCF",
                "ICSCF",
                "SCSCF",
                "TAS",
                "HSS",
                "RRBS",
                "PCRF"
              ]

REF_CDR_INPUT_EXT = [
                       ".tdr",
                       ".tdr",
                       ".tdr",
                       ".tdr",
                       ".tdr",
                       ".cdr",
                       ".tdr"
                     ]
##############eg:-CDR_FIELDS= [ "1-3,6-9" , "1-5,10-30" ]##############
#####Should be in the order in which Reference CDR Path is Given#######


CDR_FIELDS= [ "2-6,9-11,14,17-57,59,60,62,63,65-68,70,72-76,78-82,84-86,90-97,99-110,112-123,125-127", "2-6,9-11,14,17-57,59,60,62,63,65-68,70,72-76,78-82,84-86,90-97,99-110,112-123,125-127", "2-6,9-11,14,17-57,59,60,62,63,65-68,70,72-76,78-82,84-86,90-97,99-110,112-123,125-127", "2-6,9-11,14,17-57,59,60,62,63,65-68,72,75-76,78-82,84-86,90-97,99-110,112-123,125-127", "2,5-141,143-174", "1-25,32-38,40-41,43-48,49-51,52-55,57-65,67-68,70-81", "2-5" ]

DELIMITERS= [ ",", ",", ",", ",", ",", ",", "," ]

TOTAL_CDR_COUNT= [ 129, 129, 129, 129, 175, 100, 94 ]

MIGRATION_FLAG=0


########### REF_CDR_PATTERN_0 indicates CDR Field Description for First Reference CDR Path 
########### REF_CDR_PATTERN_1 indicates CDR Field Description for Second Reference CDR Path

REF_CDR_PATTERN_0=[
"Datatype",
"Protocoltype",
"EdrDirectionstatus",
"OpCode",
"Reference",
"From",
"To",
"Contact",
"ContentLength",
"IpsecFlag",
"RemotePartyIpPort",
"TransportType",
"RequestURI",
"CallingPartySsn",
"OriginatingModule",
"UeOverIpsec",
"ServerIpsecSts",
"RejectionStatus",
"UserAgent",
"RequestType",
"RequestMsisdn",
"RequestImsi",
"OtherParty",
"MessageStatus",
"ByeReasonhdr",
"SipMethodType",
"ErrorCode",
"ErrorDesc",
"ErrorAddDesc",
"RequestDomain",
"PathHeader",
"NetworkId",
"ExpiryTime",
"CallType",
"PVisitedNwId",
"DiamReq",
"DiamErrCode",
"DiamErrDesc",
"RegistrationType",
"SubscriptionType",
"SubscriptionEvent",
"AsName",
"ScscfName",
"SipServiceRoute",
"IcscfDomainNameRcvd",
"IcscfProxyRegister",
"IcscfProxyErrMsg",
"IcscfSubscriberDetails",
"IcscfSubscriberPortOut",
"IcscfRegistratinStatus",
"IcscfPortedOutPrefix",
"TasCallPartyPortOutInd",
"TasRrbsRespCode",
"TasRrbsAnnounId",
"TasCallBarInd",
"TasCallFwrdInd",
"TasCallFwrdUsr",
"TasCallHoldInd",
"TascallWaiting",
"TasUsedUnits",
"TasMrfAnnunId",
"TasForwRecordNum",
"TasForwCallRef",
"TasForwExchangeId",
"TasForwFwdedToNum",
"TasAccessNetworkInfo",
"TasForwCauseForForwarding",
"TasServingNode",
"TasCallFeature",
"TasAccumulatedGrantMoney",
"TasFreeUnits",
"TasFreeZoneUnits",
"TasFreeZoneId",
"TasOriginatingCallingPty",
"TasLanguageId",
"TasPremiumCharge",
"TasPremiumDuration",
"TasServingCell",
"TasPremiunUniqueId",
"TasSubsRegd",
"TasAdditionalInfo",
"TasImporterPrefix",
"TasAccountedUnits",
"TasRecentGrantMoney",
"TasRRBSCriticalTdrIndiction",
"TasCallInd",
"ScscfReqScscfName",
"ScscfSarServerAssigmentType",
"ScscfSaaImplicitImpu",
"ScscfIfcId",
"ScscfMediaProfId",
"ScscfServiceId",
"pcscf_sip_method",
"pcscf_ip_can_type",
"pcscf_rat_type",
"RemoteErrCode",
"NewResrvOne",
"NewResrvTwo",
"NewResrvThree",
"NewResrvFour",
"NewResrvFive",
"NewResrvSix",
"NewResrvSeven",
"OamErrorCode",
"OamFreeFormatData",
"RemoteRealm",
"LocalHost",
"LocalRealm",
"HssBegin"
]

REF_CDR_PATTERN_1=[
"Datatype",
"Protocoltype",
"EdrDirectionstatus",
"OpCode",
"Reference",
"From",
"To",
"Contact",
"ContentLength",
"IpsecFlag",
"RemotePartyIpPort",
"TransportType",
"RequestURI",
"CallingPartySsn",
"OriginatingModule",
"UeOverIpsec",
"ServerIpsecSts",
"RejectionStatus",
"UserAgent",
"RequestType",
"RequestMsisdn",
"RequestImsi",
"OtherParty",
"MessageStatus",
"ByeReasonhdr",
"SipMethodType",
"ErrorCode",
"ErrorDesc",
"ErrorAddDesc",
"RequestDomain",
"PathHeader",
"NetworkId",
"ExpiryTime",
"CallType",
"PVisitedNwId",
"DiamReq",
"DiamErrCode",
"DiamErrDesc",
"RegistrationType",
"SubscriptionType",
"SubscriptionEvent",
"AsName",
"ScscfName",
"SipServiceRoute",
"IcscfDomainNameRcvd",
"IcscfProxyRegister",
"IcscfProxyErrMsg",
"IcscfSubscriberDetails",
"IcscfSubscriberPortOut",
"IcscfRegistratinStatus",
"IcscfPortedOutPrefix",
"TasCallPartyPortOutInd",
"TasRrbsRespCode",
"TasRrbsAnnounId",
"TasCallBarInd",
"TasCallFwrdInd",
"TasCallFwrdUsr",
"TasCallHoldInd",
"TascallWaiting",
"TasUsedUnits",
"TasMrfAnnunId",
"TasForwRecordNum",
"TasForwCallRef",
"TasForwExchangeId",
"TasForwFwdedToNum",
"TasAccessNetworkInfo",
"TasForwCauseForForwarding",
"TasServingNode",
"TasCallFeature",
"TasAccumulatedGrantMoney",
"TasFreeUnits",
"TasFreeZoneUnits",
"TasFreeZoneId",
"TasOriginatingCallingPty",
"TasLanguageId",
"TasPremiumCharge",
"TasPremiumDuration",
"TasServingCell",
"TasPremiunUniqueId",
"TasSubsRegd",
"TasAdditionalInfo",
"TasImporterPrefix",
"TasAccountedUnits",
"TasRecentGrantMoney",
"TasRRBSCriticalTdrIndiction",
"TasCallInd",
"ScscfReqScscfName",
"ScscfSarServerAssigmentType",
"ScscfSaaImplicitImpu",
"ScscfIfcId",
"ScscfMediaProfId",
"ScscfServiceId",
"pcscf_sip_method",
"pcscf_ip_can_type",
"pcscf_rat_type",
"RemoteErrCode",
"NewResrvOne",
"NewResrvTwo",
"NewResrvThree",
"NewResrvFour",
"NewResrvFive",
"NewResrvSix",
"NewResrvSeven",
"OamErrorCode",
"OamFreeFormatData",
"RemoteRealm",
"LocalHost",
"LocalRealm",
"HssBegin"
]

REF_CDR_PATTERN_2=[
"Datatype",
"Protocoltype",
"EdrDirectionstatus",
"OpCode",
"Reference",
"From",
"To",
"Contact",
"ContentLength",
"IpsecFlag",
"RemotePartyIpPort",
"TransportType",
"RequestURI",
"CallingPartySsn",
"OriginatingModule",
"UeOverIpsec",
"ServerIpsecSts",
"RejectionStatus",
"UserAgent",
"RequestType",
"RequestMsisdn",
"RequestImsi",
"OtherParty",
"MessageStatus",
"ByeReasonhdr",
"SipMethodType",
"ErrorCode",
"ErrorDesc",
"ErrorAddDesc",
"RequestDomain",
"PathHeader",
"NetworkId",
"ExpiryTime",
"CallType",
"PVisitedNwId",
"DiamReq",
"DiamErrCode",
"DiamErrDesc",
"RegistrationType",
"SubscriptionType",
"SubscriptionEvent",
"AsName",
"ScscfName",
"SipServiceRoute",
"IcscfDomainNameRcvd",
"IcscfProxyRegister",
"IcscfProxyErrMsg",
"IcscfSubscriberDetails",
"IcscfSubscriberPortOut",
"IcscfRegistratinStatus",
"IcscfPortedOutPrefix",
"TasCallPartyPortOutInd",
"TasRrbsRespCode",
"TasRrbsAnnounId",
"TasCallBarInd",
"TasCallFwrdInd",
"TasCallFwrdUsr",
"TasCallHoldInd",
"TascallWaiting",
"TasUsedUnits",
"TasMrfAnnunId",
"TasForwRecordNum",
"TasForwCallRef",
"TasForwExchangeId",
"TasForwFwdedToNum",
"TasAccessNetworkInfo",
"TasForwCauseForForwarding",
"TasServingNode",
"TasCallFeature",
"TasAccumulatedGrantMoney",
"TasFreeUnits",
"TasFreeZoneUnits",
"TasFreeZoneId",
"TasOriginatingCallingPty",
"TasLanguageId",
"TasPremiumCharge",
"TasPremiumDuration",
"TasServingCell",
"TasPremiunUniqueId",
"TasSubsRegd",
"TasAdditionalInfo",
"TasImporterPrefix",
"TasAccountedUnits",
"TasRecentGrantMoney",
"TasRRBSCriticalTdrIndiction",
"TasCallInd",
"ScscfReqScscfName",
"ScscfSarServerAssigmentType",
"ScscfSaaImplicitImpu",
"ScscfIfcId",
"ScscfMediaProfId",
"ScscfServiceId",
"pcscf_sip_method",
"pcscf_ip_can_type",
"pcscf_rat_type",
"RemoteErrCode",
"NewResrvOne",
"NewResrvTwo",
"NewResrvThree",
"NewResrvFour",
"NewResrvFive",
"NewResrvSix",
"NewResrvSeven",
"OamErrorCode",
"OamFreeFormatData",
"RemoteRealm",
"LocalHost",
"LocalRealm",
"HssBegin"
]

REF_CDR_PATTERN_3=[
"Datatype",
"Protocoltype",
"EdrDirectionstatus",
"OpCode",
"Reference",
"From",
"To",
"Contact",
"ContentLength",
"IpsecFlag",
"RemotePartyIpPort",
"TransportType",
"RequestURI",
"CallingPartySsn",
"OriginatingModule",
"UeOverIpsec",
"ServerIpsecSts",
"RejectionStatus",
"UserAgent",
"RequestType",
"RequestMsisdn",
"RequestImsi",
"OtherParty",
"MessageStatus",
"ByeReasonhdr",
"SipMethodType",
"ErrorCode",
"ErrorDesc",
"ErrorAddDesc",
"RequestDomain",
"PathHeader",
"NetworkId",
"ExpiryTime",
"CallType",
"PVisitedNwId",
"DiamReq",
"DiamErrCode",
"DiamErrDesc",
"RegistrationType",
"SubscriptionType",
"SubscriptionEvent",
"AsName",
"ScscfName",
"SipServiceRoute",
"IcscfDomainNameRcvd",
"IcscfProxyRegister",
"IcscfProxyErrMsg",
"IcscfSubscriberDetails",
"IcscfSubscriberPortOut",
"IcscfRegistratinStatus",
"IcscfPortedOutPrefix",
"TasCallPartyPortOutInd",
"TasRrbsRespCode",
"TasRrbsAnnounId",
"TasCallBarInd",
"TasCallFwrdInd",
"TasCallFwrdUsr",
"TasCallHoldInd",
"TascallWaiting",
"TasMrfAnnunId",
"TasForwExchangeId",
"TasForwFwdedToNum",
"TasAccessNetworkInfo",
"TasForwCauseForForwarding",
"TasServingNode",
"TasCallFeature",
"TasAccumulatedGrantMoney",
"TasFreeUnits",
"TasFreeZoneUnits",
"TasFreeZoneId",
"TasOriginatingCallingPty",
"TasLanguageId",
"TasPremiumCharge",
"TasPremiumDuration",
"TasServingCell",
"TasPremiunUniqueId",
"TasSubsRegd",
"TasAdditionalInfo",
"TasImporterPrefix",
"TasAccountedUnits",
"TasRecentGrantMoney",
"TasRRBSCriticalTdrIndiction",
"TasCallInd",
"ScscfReqScscfName",
"ScscfSarServerAssigmentType",
"ScscfSaaImplicitImpu",
"ScscfIfcId",
"ScscfMediaProfId",
"ScscfServiceId",
"pcscf_sip_method",
"pcscf_ip_can_type",
"pcscf_rat_type",
"RemoteErrCode",
"NewResrvOne",
"NewResrvTwo",
"NewResrvThree",
"NewResrvFour",
"NewResrvFive",
"NewResrvSix",
"NewResrvSeven",
"OamErrorCode",
"OamFreeFormatData",
"RemoteRealm",
"LocalHost",
"LocalRealm",
"HssBegin"
]

REF_CDR_PATTERN_4=[
"OpCode",
"MapVersion",
"CallingParty",
"CallingPartySsn",
"OriginatingModule",
"RequestType",
"RequestMsisdn",
"RequestImsi",
"MessageStatus",
"ErrorCode",
"ErrorDesc",
"Lmsi",
"RequestDomain",
"PartnerType",
"MscAddress",
"VlrAddress",
"SgsnIpAddress",
"SgsnAddress",
"GgsnIpAddress",
"GgsnAddress",
"LocalAddress",
"OpenCnfVersionRcvd",
"Imei",
"SriGmscAddress",
"SriCallRefNum",
"SriSuppressTcsi",
"SriPsiOrPrnFlag",
"SriPsiOrPrnErr",
"SriMsrn",
"SriForwardType",
"SriFtn",
"SsmSScode",
"SsmBScode",
"SsmBStype",
"SsmFtn",
"SsmFtnSubAddress",
"SsmNoRepTimer",
"SsmNbrUser",
"SsmDefPriority",
"SsmUssdServCode",
"SsmUssdGwAddress",
"SsmActiveMsisdn",
"SiGsmscfAddress",
"SiReqInfo",
"SiSgsnNotReachableReason",
"AucNumVectorsRequested",
"AucNumVectorsSent",
"AucResyncInfo",
"AucAfrRand",
"AucAfrReAttempt",
"AucAfrAccessType",
"AucAfrFailureCause",
"OamNumImsiPrefixes",
"OamImsiPrefixes",
"SmsmSmscAddress",
"SmsmPriorityFlag",
"SmsmGprsFlag",
"SmsmStoredMsisdn",
"SmsmMwStatus",
"SmsmAlertReason",
"SmsmGprsAlertReason",
"SmsmSmDeliveryOutcome",
"SmsmGprsDeliveryOutcome",
"OamRequestType",
"OamTransactionId",
"OamErrorCode",
"OamErrorDesc",
"OamFreeFormatTdrData",
"MmFirstUL",
"MmMsisdnAllocStatus",
"MmNetworkID",
"MmPartnerNetworkID",
"MmPrimaryImsi",
"MmPrimaryMsisdn",
"MmPreviousNode",
"MmPreviousImei",
"MmNam",
"SriTcsiStatus",
"DbErrorCode",
"DbErrorDesc",
"ApplCtxt",
"RESRV1",
"RESRV2",
"RESRV3",
"RESRV4",
"RESRV5",
"MmLocalImsi",
"MmLocalMsisdn",
"MmLocalNumAllocStatus",
"MmImsiBurntType",
"SIMS_98servertructure",
"RESRV7",
"RESRV8",
"HlrReserv1",
"HlrReserv2",
"HlrReserv3",
"HlrReserv4",
"HlrReserv5",
"AccountId",
"IccId",
"OriginatingHlrGt",
"HlrReserv9",
"HlrReserv10",
"HssBeginIndex",
"ErrorDiagnostic",
"RemoteHost",
"RemoteRealm",
"LocalHost",
"LocalRealm",
"RemoteSuppFeature1",
"RemoteSuppFeature2",
"LocalExtraSuppFeature",
"LocalSuppFeature1",
"LocalSuppFeature2",
"LocalExtraSuppFeature",
"RequestFlags",
"AnswerFlags",
"UlrVplmnId",
"UlrRatType",
"UlrMeId",
"UlrSoftwareVersion",
"UlrUeSrvccCapability",
"UlrHomogenousSupportImsOverPs",
"UlrGmlcAddress",
"UlrRowIdOne",
"UlrRowIdTwo",
"UlrRowIdThree",
"UlrRowIdFour",
"NorMip6AiHaFamily1",
"NorMip6AiHaAddress1",
"NorMip6AiHaFamily2",
"NorMip6AiHaAddress2",
"NorMip6AiHaDestRealm",
"NorMip6AiHaDestHost",
"NorContextId",
"NorServiceSelection",
"NorAlertReason",
"ClrCancellationType",
"LocationChangeInd",
"CurrentMccMnc",
"PreviousRoamingZone",
"PreviousMccMnc",
"ResrvPos147",
"ResrvPos148",
"ResrvPos149",
"ResrvPos150",
"ResrvPos151",
"ResrvPos152",
"ResrvPos153",
"ResrvPos154",
"RemoteErrCode",
"LocalTracingFlag",
"AlternateFlagCampaignId",
"AlternatePrimaryImsi",
"AlternatePrimaryImsi2",
"MemcGet",
"MemcSet",
"OamDestAlocType",
"NewResrvSeven",
"NewResrvEight",
"ServerScscfName",
"SarServerAssignType",
"SarUserDataAvail",
"UarVisitednkid",
"UarAuthorizationType",
"UarCapabilityTemplId",
"ImsProfileID",
"UdrPubIdentity",
"UdrMsisdn",
"UdrAuthSessionState"
]

REF_CDR_PATTERN_5=[
"CDR Type",
"Network ID",
"Call Type",
"Call Feature",
"Tariff Plan ID",
"Service ID",
"Calling party number",
"Called party number",
"Charged party number",
"IMS_98serverI",
"Serving Node",
"Mcc",
"Mnc",
"Lac",
"CellId",
"Cell Zone Code",
"Cell Zone Name",
"Original called party number",
"Destination zone code",
"Destination area code",
"Destination zone name",
"Roaming area code",
"Roaming zone name",
"Roam Flag",
"Roaming node",
"Initial Account balance",
"Call charge",
"Final Account balance",
"Free minutes account balance",
"AccId",
"DeptId",
"Free Zone Id",
"Last Top up Type",
"Bundle Code",
"Ring Duration",
"Ring Duration Indicator",
"National Bundle code",
"National Used Minutes",
"National Charge",
"Pool Number",
"Bundle used Seconds",
"Bundle Call Charge",
"Bundle Balance",
"Bundle Plan ID",
"Final Unit Indicator",
"NCALL free units",
"Local Roam Country Code",
"Bucket type",
"Conversion Unit",
"Intial Free units",
"Subscriber Type",
"Call Forwarding Indicator",
"CDR Sequence Number",
"Account Id",
"Announcement Time",
"Family Id",
"CS free Mins",
"Free units detected",
"CALL INDICATOR",
"CONNECT NUMBER",
"Dialed number",
"Service description",
"Alternate Plan Id",
"Serving Node Name",
"Fixed charge ",
"Fixed charge Resource Impact",
"Bundle Version Name",
"FLH Reward slab id",
"Bundle version ID",
"Rate Id"
]

REF_CDR_PATTERN_6=[
"Datatype",
"Protocoltype",
"EdrDirectionstatus",
"OpCode"
]
