#############-->>Enter the path to save automation report <--################
REMOTE_AUTOPATH = "/opt/product/testteam/Products/AUTOMATION/IMS_SOLARIS_IPV6_EXP_MSTACK/Automation_folder/delcom-script"
REMOTE_AUTOSCRIPT = "startstopscript.sh"
SIPP_USERNAME = "testteam"
SIPP_PASSWORD = "Plintron1"
SIPP_COMMAND = "/opt/sipp/"
SIPP_PROMPT = "#"
SIPP_PIDGREP = "Background"
ID_RSA_SIPP = "/opt/product/AUTOMATION/.ssh/id_rsa"
SIPP_IP_ADDRESS = "192.168.151.142"
SIPP_ALIAS = "SIPP"


#############-->>SEAGULL path Details <--################
LD_LIBRARY_PATH= "/usr/local/bin"
SIPP_RUN= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/RUN"
SIPP_SCENARIO= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/SCENARIO"
SIPP_INF= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/INF"
SIPP_LOG= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/LOG"
SIPP_COMPLOGPATH= "/opt/product/AUTOMATION/AUTOMATION_RESULTS/IMS_SOLARIS_IPV6_EXP_MSTACK/COMPLETED_IMS_LOG"
SIPP_PROCESS= "IMSSIPP"
SIPP_PROCESS_REMOTE= "AUTO_IMS"
SIPP_CLIENT_PROCESS= "IMSclientSIPP"
SIPP_SERVER_PROCESS= "IMSserverSIPP"
SIPP_SERVER2_PROCESS= "IMSserver2SIPP"
SIPP_SERVER3_PROCESS= "IMSserver2SIPP"

SIPP_CLIENT2_PROCESS= "IMSclient2SIPP"
SIPP_SLEEP=2
SIPP_TIMEOUT=60
SIPP_PIDGREP = "Background"
SIPP_TMP = "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/TMP/"
SIPPLOG_RESULT= "NULL"
SIPPSTAT_RESULT= "None"
CLIENT_SIPPLOG_RESULT= "NULL"
CLIENT_SIPPSTAT_RESULT= "NULL"
SERVER_SIPPLOG_RESULT= "NULL"
SERVER_SIPPSTAT_RESULT= "NULL"
SERVER2_SIPPLOG_RESULT= "NULL"
SERVER2_SIPPSTAT_RESULT= "NULL"
CLIENT_SERVER_SCENARIO= 0
SIPP_REMOTE_PATH= "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/"
SIPP_PROTO_GREP = "egrep -i 'REGISTER|CSeq:|401 Unauthorized|200 OK|SUBSCRIBE|NOTIFY '"
SIPP_PROTO_GREP_END_STRING = " "
SIPP_TEMP_PATH = "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/TEMP/"
SIPP_EXP_PATH = "/opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/INPUTS/SIPP/PROTO/"
SIPP_PROTO_VALIDATION=0
SIPP_PROTO_VALIDATION_TYPE=1



############-->>STATUS FLAGS-->>#############
PASS= "DONE"
FAIL= "FAIL"
NOPREDB= "NULL"



############LD Library path#############
SIPPENV= "export LD_LIBRARY_PATH=/usr/local/bin"
##############-msgchecK Validation#############
msgchk = "NO"
msgno = " "
##############-msgchecK Validation#############
PROGDIR = "/usr/local/bin"
SIPP_RESULT= "PASS"
