*** Settings ***
Documentation     IMS_VoLTE_SS_ODB_WITHOUT_ANNOUNCEMENT
Suite Setup       SUITE STARTUP
Suite teardown    CLOSE EXISTING CONNECTION
Test Teardown     TEST STOP
Force Tags        IMS_VoLTE_SS_ODB_WITHOUT_ANNOUNCEMENT
Default Tags      P2
Test Timeout      5 minutes
Library           Collections
Library           SSHLibrary
Library           OperatingSystem
Library           String
Library           BuiltIn
Library           DateTime
Library           DatabaseLibrary
Library           XML
Library           Rammbock
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_MGTS_CONNECT.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_START_STOP.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_APP_CONNECT.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_SEAGULL_RUN.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_SIPP_MODULE.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_DB_MODULE.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_LOGGING.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_CDR_MODULE.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_SUITE_MODULE.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_PCAP_MODULE.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_SHELL_MODULE.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_REMOTE_APP.robot
Resource          /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/MODULES/AUTO_TESTCASE_MODULE.robot
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_MAIN_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_LOGGING_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_CDR_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_DB_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_SEAGULL_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_PCAP_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_SHELL_COMMAND_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_REMOTE_APP_DETAILS.py
Variables         /opt/product/AUTOMATION/TEST_AUTOMATION_FRAMEWORK/IMS_SOLARIS_IPV6_EXP_MSTACK/CONFIG/AUTO_SIPP_DETAILS.py

*** Variables ***
${LOGGER_Validation}    1
${CDR_Validation}    0
${PRE_DB_Validation}    1
${POST_DB_QUERY_Validation}    1

*** Test Cases ***

AUTO_IMS_REG_001
    [Documentation]    "To Verify IMS Re_REGISTRATON."
    [Tags]    CRIT_P1_IMS_REG
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_REG_001
    Set Test Variable    @{PCAP_XML_CONVERSION_END_STRING}    -Y sip -V | sed -n '/Session Initiation Protocol/,/Content-Length/p' | sed 's/^ *//' | sed '/Session Initiation Protocol/i ###############@@@@@@@@NEW SIP MESSAGE@@@@@@@@@##################\n'
    Set Test Variable    ${PCAP_PROTO_GREP}    egrep -hi 'Request-Line:|Status-Line:|CSeq:' 
    Set Test Variable    ${PCAP_PROTO_GREP_END_STRING}    | egrep -v 'egrep|OPTIONS'
    Set Test Variable    ${PROTOCOL_VALIDATION_TYPE}    1
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_REG_SS_OUTGOING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify IMS VoLTE Registration of SS OUTGOING CALL BARRING CALLING msisdn WITHOUT ANNOUNCEMENT."
    [Tags]    CRIT_P1_IMS_VoLTE_CALL_REG
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_REG_SS_OUTGOING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_REG_SS_INCOMING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify IMS VoLTE Registration of SS INCOMING CALL BARRING CALLED msisdn WITHOUT_ANNOUNCEMENT."
    [Tags]    CRIT_P1_IMS_VoLTE_CALL_REG
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_REG_SS_INCOMING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify basic ims VoLTE SS OUTGOING_CALL_BARRING scenario WITHOUT_ANNOUNCEMENT."
    [Tags]    CRIT_P1_IMS_VoLTE_MOCALL
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    Set Test Variable    @{PCAP_XML_CONVERSION_END_STRING}    -Y sip -V | sed -n '/Session Initiation Protocol/,/Content-Length/p' | sed 's/^ *//' | sed '/Session Initiation Protocol/i ###############@@@@@@@@NEW SIP MESSAGE@@@@@@@@@##################\n'
    Set Test Variable    ${PCAP_PROTO_GREP}    egrep -hi 'Request-Line:|Status-Line:|CSeq:' 
    Set Test Variable    ${PCAP_PROTO_GREP_END_STRING}    | egrep -v 'egrep|OPTIONS'
    Set Test Variable    ${PROTOCOL_VALIDATION_TYPE}    1
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_SS_INCOMING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify basic ims VoLTE MT Incoming call barring scenario WITHOUT_ANNOUNCEMENT."
    [Tags]    CRIT_P1_IMS_VoLTE_MTCALL
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_SS_INCOMING_CALL_BARRING_WITHOUT_ANNOUNCEMENT
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_INTERNATIONAL_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify basic ims VoLTE SS OUTGOING_CALL_BARRING INTERNATIONAL scenario WITHOUT_ANNOUNCEMENT."
    [Tags]    CRIT_P1_IMS_VoLTE_MOCALL
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_INTERNATIONAL_WITHOUT_ANNOUNCEMENT
    Set Test Variable    @{PCAP_XML_CONVERSION_END_STRING}    -Y sip -V | sed -n '/Session Initiation Protocol/,/Content-Length/p' | sed 's/^ *//' | sed '/Session Initiation Protocol/i ###############@@@@@@@@NEW SIP MESSAGE@@@@@@@@@##################\n'
    Set Test Variable    ${PCAP_PROTO_GREP}    egrep -hi 'Request-Line:|Status-Line:|CSeq:' 
    Set Test Variable    ${PCAP_PROTO_GREP_END_STRING}    | egrep -v 'egrep|OPTIONS'
    Set Test Variable    ${PROTOCOL_VALIDATION_TYPE}    1
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_TEL_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify basic ims VoLTE SS OUTGOING_CALL_BARRING scenario WITHOUT_ANNOUNCEMENT with To Header as Tel URI."
    [Tags]    CRIT_P1_IMS_VoLTE_MOCALL
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_TEL_WITHOUT_ANNOUNCEMENT
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_TEL_INTERNATIONAL_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify basic ims VoLTE SS OUTGOING_CALL_BARRING INTERNATIONAL scenario WITHOUT_ANNOUNCEMENT with To Header as Tel URI."
    [Tags]    CRIT_P1_IMS_VoLTE_MOCALL
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_SS_OUTGOING_CALL_BARRING_TEL_INTERNATIONAL_WITHOUT_ANNOUNCEMENT
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}

AUTO_IMS_VoLTE_SS_INCOMING_CALL_BARRING_TEL_WITHOUT_ANNOUNCEMENT
    [Documentation]    "To verify basic ims VoLTE MT Incoming call barring scenario WITHOUT_ANNOUNCEMENT with To Header as Tel URI."
    [Tags]    CRIT_P1_IMS_VoLTE_MTCALL
    Set Test Variable    ${STATE_MACHINE}    AUTO_IMS_VoLTE_SS_INCOMING_CALL_BARRING_TEL_WITHOUT_ANNOUNCEMENT
    ${TC_RESULT} =    START IMS AUTO
    log    ${TC_RESULT}


*** Keywords ***
